

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: check file
        id: check_file
        uses: andstor/file-existence-action@v1
        with:
          files: "test_bool.txt"
          
      - name: Doxygencreate
        if: steps.check_file.outputs.files_exists =='true'
        run: |
          ls
          cd output
          mkdir fs
          #sudo apt update
          #sudo apt-get install doxygen
          #doxygen config  
          
          
          
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
      # Include all JS files from the `dist` directory
          file-path: output/*
          commit-msg: Update resources
          github-token: ${{ secrets.API_TOKEN_GITHUB }}
     # - name: Doxygencreate
     #   uses: mattnotmitt/doxygen-action@v1.9.2
     #   with:
      #    working-directory: 'submodule/'
      #    doxyfile-path: 'docs/Doxygen'
 
#
     # - name: upload
     #   uses: cpina/github-action-push-to-another-repository@main
     #   env:
      #    API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
     #   with:
      #    source-directory: output/
      #    destination-github-username: 'EnderWarik'
      #    destination-repository-name: 'OpiLab2'
      #    user-email: 2020102437@pnu.edu.ru
      #    target-directory: output/
       #   target-branch: main

  doxygenpush:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: output/
          destination-github-username: 'EnderWarik'
          destination-repository-name: 'OpiLab2.io'
          user-email: 2020102437@pnu.edu.ru
          target-branch: main
