

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: check file
        id: check_file
        uses: andstor/file-existence-action@v1
        with:
          files: "test_bool.txt"
          
      - name: Run a one-line script
        if: steps.check_file.outputs.files_exists =='true'
        run: echo Hello, world!

   #   - name: Run a multi-line script
    #    run: |
     #     echo Add other actions to build,
      #    echo test, and deploy your project.
          # This is a basic workflow to help you get started with Actions

  doxygencreate:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'OpiLab2'
          destination-github-username: 'EnderWarik'
          destination-repository-name: 'OpiLab2.io'
          user-email: 2020102437@pnu.edu.ru
          target-branch: main
