

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: check file
        id: check_file
        uses: andstor/file-existence-action@v1
        with:
          files: "test_bool.txt"
          
      - name: Run a one-line script
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo Hello, world!

   #   - name: Run a multi-line script
    #    run: |
     #     echo Add other actions to build,
      #    echo test, and deploy your project.
          # This is a basic workflow to help you get started with Actions

#  doxygencreate:
#    runs-on: ubuntu-latest
  #  steps:
# Runs a single command using the runners shell
  #  - name: Run a one-line script
    #  run: doxygen config
