

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: check file
        id: check_file
        uses: andstor/file-existence-action@v1
        with:
          files: "test_bool.txt"
          
      - name: Doxygencreate
        if: steps.check_file.outputs.files_exists =='true'
        run: |
          sudo apt update
          sudo apt-get install doxygen
          doxygen config  

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: output/
          destination-github-username: 'EnderWarik'
          destination-repository-name: 'OpiLab2.io'
          user-email: 2020102437@pnu.edu.ru
          target-branch: main
          
      - name: Init
        run: |
          sudo apt-get install g++-10
          g++ -dumpversion
          g++ -I ./ OPI.cpp -o test.exe
          ls
          
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.exe


